name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
permissions:
  # https://github.community/t/permissions-nesecary-to-comment-on-a-pr/179047/5
  pull-requests: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', 'pypy3.9' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tools
        run: python3 -m pip install --upgrade build
      - name: Install
        run: pip install -r requirements.txt
      - name: Install sphinx
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
      - name: Check with pyflakes
        run: |
          pip install pyflakes
          pyflakes `find . -name "*.py"`
      - name: Install coverage
        run: pip install coverage
      - name: Test
        run: |
          python3 -m coverage run -a -m unittest discover -v src
      - name: Document
        run: |
          sphinx-apidoc -o docs/ -f -a -e src/ --doc-project "Python SDK for Arcaflow"
          make -C docs html
      - name: Run example plugin
        run: python3 -m coverage run -a ./example_plugin.py -f example.yaml
      - name: Run example plugin test
        run: python3 -m coverage run -a ./test_example_plugin.py
      - name: Collect coverage report
        run: |
          python3 -m coverage html
      - name: Update version number
        if: startsWith(github.ref, 'refs/tags/')
        run: sed -i -e "s/0.0.0/${GITHUB_REF##*/}/" pyproject.toml
      - name: Build
        run: python3 -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: htmlcov
          if-no-files-found: error
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Install twine
        run: pip install -U twine
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
          TWINE_NON_INTERACTIVE: true
        run: twine upload dist/*
